---
- name: install apache2
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - apache2
  tags: pkg-install
  become: true

- name: install PHP5 and modules
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-curl
    - php5-cli
    - php5-mysql
  tags: pkg-install
  become: true
