language: php
php:
  - '7.0'
os: linux
dist: xenial

install:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  - cd .ansible && /bin/bash ./start.sh
