---
- name: update repositories cache
  apt:
    update_cache: yes
  tags: pkg-install
  become: true

- name: install common software
  apt:
    name={{ item }}
    state=present
  loop:
    - git
  tags: pkg-install
  become: true
