---
- hosts: dev
  connection: local
  gather_facts: no

  pre_tasks:
    - name: update repositories cache
      apt:
        update_cache: yes
      tags: pkg-install
      become: true

  roles:
    - { role: app }
