---
- name: install apache2
  apt:
    name:  "{{ item }}"
    state: present
  loop:
    - apache2
  tags: pkg-install
  become: true

- name: install PHP5 and modules
  apt:
    name:  "{{ item }}"
    state: present
  loop:
    - php7.0
    - php7.0-curl
    - php7.0-cli
    - php7.0-mysql
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-gd
    - libapache2-mod-php7.0
  tags: pkg-install
  become: true

- name: enable apache modules
  apache2_module:
    name={{ item }}
    state=present
  loop:
    - rewrite
    - ssl
  become: true

- name: create filesystem for virtual hosts
  file:
    path="{{ item }}"
    state=directory
  loop:
    - "{{ vhost_home_dir }}"
    - "{{ vhost_logs_dir }}"
  become: true
