---
- name: install common software
  apt:
    name={{ item }}
    state=present
  loop:
    - git
    - python-mysqldb
  tags: pkg-install
  become: true

- name: set Europe/Moscow time zone
  timezone:
    name: Europe/Moscow
  become: true
