env: stage

deploy_user: achernov
app_env: production
project_root_dir: "{{ vhost_home_dir }}/sf4project/stage"
app_vhost: stage.sf4project.com

mysql_db_name: sf4project_stage
mysql_set_user: sf4project_stage
mysql_set_password: sf4project_stage
